'use client';

import React, { useState } from 'react';
import { formatIndianNumber } from '@fno/shared';
import type { SentimentLabel, NextDayBias, InstitutionalFlowPrediction, PredictionAccuracyWindow } from '@fno/shared';
import { useInstitutionalFlow, usePredictionAccuracy } from '@/lib/use-institutional-flow';
import { useMarketStore } from '@/stores';

const SENTIMENT_META: Record<SentimentLabel, { label: string; color: string; barColor: string }> = {
  EXTREMELY_BEARISH: { label: 'Extremely Bearish', color: 'text-red-400', barColor: 'bg-red-500' },
  BEARISH: { label: 'Bearish', color: 'text-red-400', barColor: 'bg-red-400' },
  NEUTRAL: { label: 'Neutral', color: 'text-gray-300 light:text-slate-600', barColor: 'bg-gray-400' },
  BULLISH: { label: 'Bullish', color: 'text-emerald-400', barColor: 'bg-emerald-400' },
  EXTREMELY_BULLISH: { label: 'Extremely Bullish', color: 'text-emerald-400', barColor: 'bg-emerald-500' },
};

export function InstitutionalFlowPage() {
  const { snapshot, biases, commentary, loading, isLive } = useInstitutionalFlow();
  const setActiveTab = useMarketStore((s) => s.setActiveTab);
  const [accuracySymbol, setAccuracySymbol] = useState<'NIFTY' | 'BANKNIFTY'>('NIFTY');
  const { predictions, accuracy, loading: accuracyLoading } = usePredictionAccuracy(accuracySymbol);

  return (
    <div className="p-4 space-y-4 min-h-full">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-lg font-bold text-gray-100 light:text-slate-900">Institutional Flow Intelligence</h1>
          <p className="text-xs text-gray-500 light:text-slate-500 mt-0.5">
            Sentiment, next-day bias, and prediction tracking built from what's genuinely live — India VIX, PCR, F&O universe OI activity, and the existing market-bias engine.
          </p>
        </div>
        <span className="flex items-center gap-1.5 text-[11px] text-gray-500 light:text-slate-500">
          <span className={`w-1.5 h-1.5 rounded-full ${isLive ? 'bg-emerald-400 animate-pulse' : 'bg-gray-600 light:bg-slate-300'}`} />
          {isLive ? 'Live' : loading ? 'Loading…' : 'Unreachable'}
        </span>
      </div>

      {!isLive && !loading && (
        <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl px-4 py-2.5 text-amber-400 light:text-amber-700 text-xs font-medium">
          ⚠️ Backend unreachable — nothing to show right now.
        </div>
      )}

      {/* Section 4: Smart Sentiment Engine */}
      {snapshot && (
        <div className="grid grid-cols-1 xl:grid-cols-3 gap-3">
          <div className="xl:col-span-1">
            <SentimentGauge score={snapshot.sentimentScore} label={snapshot.sentimentLabel} confidence={snapshot.confidenceScore} />
          </div>
          <div className="xl:col-span-2">
            <SentimentBreakdown snapshot={snapshot} />
          </div>
        </div>
      )}

      {/* Section 5: Next-Day Market Bias Engine */}
      <SectionHeader title="Next-Day Market Bias Engine" subtitle="Gap / trend / range / volatility read from the current bias, regime, and India VIX — not a statistical model." />
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {biases.map((b) => (
          <NextDayBiasCard key={b.symbol} bias={b} />
        ))}
        {biases.length === 0 && loading && (
          <>
            <SkeletonCard />
            <SkeletonCard />
          </>
        )}
      </div>

      {/* Section 6: AI Market Commentary */}
      <SectionHeader title="AI Market Commentary" subtitle="Generated by Claude, grounded only in the real data above." />
      {commentary && <CommentaryCard commentary={commentary} />}

      {/* Section 7: Historical Accuracy Tracking */}
      <SectionHeader title="Historical Accuracy Tracking" subtitle="Starts from zero real history today — honestly reads 'not enough data yet' until real trading days accumulate." />
      <AccuracySection symbol={accuracySymbol} onSymbolChange={setAccuracySymbol} predictions={predictions} accuracy={accuracy} loading={accuracyLoading} />

      {/* Section 8: Alerts Engine */}
      <SectionHeader title="Alerts Engine" subtitle="VIX spikes, PCR extremes, and unusual F&O-universe OI activity — routed through the same Telegram channel as the rest of this app's alerts." />
      <AlertsStatusCard onViewAlerts={() => setActiveTab('alerts')} />

      {/* Sections 1, 2, 3, 9: blocked on FII/DII/participant data */}
      <SectionHeader title="Institutional Flow Dashboard, FII Futures Positioning, Participant-wise OI & Screener" subtitle="Need NSE's own FII/DII cash-flow, participant-wise OI, and FII futures reports — Angel One's API doesn't carry this data." />
      <NotConnectedPanel />
    </div>
  );
}

// --- Shared layout bits ---

function SectionHeader({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <div className="pt-1">
      <h2 className="text-sm font-bold text-gray-200 light:text-slate-800">{title}</h2>
      <p className="text-[11px] text-gray-500 light:text-slate-500 mt-0.5">{subtitle}</p>
    </div>
  );
}

function Card({ children, accent = 'border-t-amber-500/50' }: { children: React.ReactNode; accent?: string }) {
  return (
    <div className={`bg-gradient-to-b from-[#151522] to-[#0d0d14] light:from-white light:to-slate-50 border border-gray-800/60 light:border-slate-200 border-t-2 ${accent} rounded-xl p-4 shadow-[0_8px_28px_-14px_rgba(0,0,0,0.75)] light:shadow-[0_4px_16px_-8px_rgba(0,0,0,0.12)]`}>
      {children}
    </div>
  );
}

function SkeletonCard() {
  return (
    <div className="bg-gradient-to-b from-[#141420] to-[#0d0d14] light:from-white light:to-slate-50 border border-gray-800/60 light:border-slate-200 rounded-xl p-4 h-40 animate-pulse" />
  );
}

// --- Section 4 ---

function SentimentGauge({ score, label, confidence }: { score: number; label: SentimentLabel; confidence: number }) {
  const meta = SENTIMENT_META[label];
  return (
    <Card accent="border-t-cyan-500/50">
      <div className="text-[10px] font-semibold text-gray-500 light:text-slate-500 uppercase tracking-wider mb-3">Market Sentiment Score</div>
      <div className={`text-4xl font-bold tabular-nums ${meta.color} mb-1`}>{score}</div>
      <div className={`text-sm font-semibold mb-3 ${meta.color}`}>{meta.label}</div>
      <div className="h-2.5 bg-gray-800 light:bg-slate-200 rounded-full overflow-hidden relative mb-1">
        <div className="absolute inset-0 flex">
          <div className="flex-1 bg-red-500/40" />
          <div className="flex-1 bg-red-400/30" />
          <div className="flex-1 bg-gray-400/20" />
          <div className="flex-1 bg-emerald-400/30" />
          <div className="flex-1 bg-emerald-500/40" />
        </div>
        <div className="absolute top-0 bottom-0 w-1 bg-white shadow-[0_0_6px_rgba(255,255,255,0.8)] rounded-full" style={{ left: `calc(${score}% - 2px)` }} />
      </div>
      <div className="flex justify-between text-[9px] text-gray-500 light:text-slate-500 mb-3">
        <span>Extremely Bearish</span>
        <span>Extremely Bullish</span>
      </div>
      <div className="flex items-center justify-between pt-2.5 border-t border-gray-800/60 light:border-slate-200 text-xs">
        <span className="text-gray-500 light:text-slate-500">Confidence Score</span>
        <span className="font-semibold text-gray-200 light:text-slate-800 tabular-nums">{confidence}/100</span>
      </div>
      <div className="flex items-center justify-between pt-1.5 text-xs">
        <span className="text-gray-500 light:text-slate-500">Institutional Conviction</span>
        <span className="text-gray-600 light:text-slate-400 italic">not connected</span>
      </div>
    </Card>
  );
}

function SentimentBreakdown({ snapshot }: { snapshot: NonNullable<ReturnType<typeof useInstitutionalFlow>['snapshot']> }) {
  return (
    <Card>
      <div className="text-[10px] font-semibold text-gray-500 light:text-slate-500 uppercase tracking-wider mb-2.5">Reasoning</div>
      <ul className="space-y-1.5 mb-3">
        {snapshot.sentimentReasoning.map((r, i) => (
          <li key={i} className="text-xs text-gray-300 light:text-slate-700 leading-snug flex gap-1.5">
            <span className="text-gray-600 light:text-slate-400">•</span>
            {r}
          </li>
        ))}
      </ul>
      <div className="flex flex-wrap gap-1.5 pt-2.5 border-t border-gray-800/60 light:border-slate-200">
        {snapshot.availableInputs.map((i) => (
          <span key={i} className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 light:text-emerald-700 font-medium">✓ {i}</span>
        ))}
        {snapshot.unavailableInputs.map((i) => (
          <span key={i} className="text-[10px] px-2 py-0.5 rounded-full bg-gray-800 light:bg-slate-100 text-gray-500 light:text-slate-400 font-medium">
            ✕ {i}
          </span>
        ))}
      </div>
    </Card>
  );
}

// --- Section 5 ---

function ProbabilityBar({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div>
      <div className="flex items-center justify-between text-[11px] mb-1">
        <span className="text-gray-400 light:text-slate-500">{label}</span>
        <span className="font-semibold text-gray-200 light:text-slate-800 tabular-nums">{value}%</span>
      </div>
      <div className="h-1.5 bg-gray-800 light:bg-slate-200 rounded-full overflow-hidden">
        <div className={`h-full rounded-full bar-animated ${color}`} style={{ width: `${value}%` }} />
      </div>
    </div>
  );
}

function NextDayBiasCard({ bias }: { bias: NextDayBias }) {
  const dirColor = bias.predictedDirection === 'BULLISH' ? 'text-emerald-400' : bias.predictedDirection === 'BEARISH' ? 'text-red-400' : 'text-gray-400';
  return (
    <Card accent="border-t-purple-500/50">
      <div className="flex items-center justify-between mb-3">
        <span className="text-sm font-bold text-gray-200 light:text-slate-800">{bias.symbol}</span>
        <span className={`text-xs font-bold ${dirColor}`}>{bias.predictedDirection} · {bias.confidence}/100</span>
      </div>
      <div className="grid grid-cols-2 gap-x-4 gap-y-2.5 mb-3">
        <ProbabilityBar label="Gap Up" value={bias.gapUpProbability} color="bg-emerald-500" />
        <ProbabilityBar label="Gap Down" value={bias.gapDownProbability} color="bg-red-500" />
        <ProbabilityBar label="Trend Day" value={bias.trendDayProbability} color="bg-cyan-500" />
        <ProbabilityBar label="Range-Bound" value={bias.rangeBoundProbability} color="bg-amber-500" />
      </div>
      <ProbabilityBar label="Volatile Session" value={bias.volatileSessionProbability} color="bg-fuchsia-500" />
      <div className="flex items-center justify-between mt-3 pt-3 border-t border-gray-800/60 light:border-slate-200">
        <span className="text-[11px] text-gray-500 light:text-slate-500">Expected Range</span>
        <span className="text-xs font-bold text-gray-200 light:text-slate-800 tabular-nums">
          {formatIndianNumber(bias.expectedRangeLow, 0)} – {formatIndianNumber(bias.expectedRangeHigh, 0)}
        </span>
      </div>
    </Card>
  );
}

// --- Section 6 ---

function CommentaryCard({ commentary }: { commentary: NonNullable<ReturnType<typeof useInstitutionalFlow>['commentary']> }) {
  if (!commentary.detailedAnalysis && !commentary.bullCase) {
    return (
      <Card>
        <p className="text-xs text-gray-500 light:text-slate-500">{commentary.oneLineSummary || 'AI commentary unavailable right now.'}</p>
      </Card>
    );
  }
  return (
    <Card accent="border-t-blue-500/50">
      <p className="text-sm font-semibold text-gray-100 light:text-slate-900 mb-3">{commentary.oneLineSummary}</p>
      <p className="text-xs text-gray-300 light:text-slate-700 leading-relaxed mb-3">{commentary.detailedAnalysis}</p>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
        <div className="bg-emerald-500/[0.06] border border-emerald-500/20 rounded-lg p-2.5">
          <div className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider mb-1">Bull Case</div>
          <p className="text-xs text-gray-300 light:text-slate-700 leading-snug">{commentary.bullCase}</p>
        </div>
        <div className="bg-red-500/[0.06] border border-red-500/20 rounded-lg p-2.5">
          <div className="text-[10px] font-bold text-red-400 uppercase tracking-wider mb-1">Bear Case</div>
          <p className="text-xs text-gray-300 light:text-slate-700 leading-snug">{commentary.bearCase}</p>
        </div>
      </div>
      {commentary.riskFactors.length > 0 && (
        <div className="pt-2.5 border-t border-gray-800/60 light:border-slate-200">
          <div className="text-[10px] font-bold text-amber-400 uppercase tracking-wider mb-1.5">Risk Factors</div>
          <ul className="space-y-1">
            {commentary.riskFactors.map((r, i) => (
              <li key={i} className="text-xs text-gray-400 light:text-slate-500 flex gap-1.5">
                <span className="text-amber-500">⚠</span>
                {r}
              </li>
            ))}
          </ul>
        </div>
      )}
    </Card>
  );
}

// --- Section 7 ---

function AccuracySection({
  symbol,
  onSymbolChange,
  predictions,
  accuracy,
  loading,
}: {
  symbol: 'NIFTY' | 'BANKNIFTY';
  onSymbolChange: (s: 'NIFTY' | 'BANKNIFTY') => void;
  predictions: InstitutionalFlowPrediction[];
  accuracy: ReturnType<typeof usePredictionAccuracy>['accuracy'];
  loading: boolean;
}) {
  return (
    <div className="space-y-3">
      <div className="flex gap-2">
        {(['NIFTY', 'BANKNIFTY'] as const).map((s) => (
          <button
            key={s}
            onClick={() => onSymbolChange(s)}
            className={`text-xs font-semibold px-3 py-1.5 rounded-lg transition-colors ${
              symbol === s ? 'bg-emerald-500/15 text-emerald-400 light:text-emerald-700' : 'bg-gray-800/50 light:bg-slate-100 text-gray-400 light:text-slate-500'
            }`}
          >
            {s}
          </button>
        ))}
      </div>

      {accuracy && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          <AccuracyWindowCard title="Last 7" window={accuracy.last7} />
          <AccuracyWindowCard title="Last 30" window={accuracy.last30} />
          <AccuracyWindowCard title="Last 100" window={accuracy.last100} />
          <AccuracyWindowCard title="All Time" window={accuracy.allTime} />
        </div>
      )}

      <Card>
        <div className="text-[10px] font-semibold text-gray-500 light:text-slate-500 uppercase tracking-wider mb-2.5">Recent Predictions — {symbol}</div>
        {predictions.length === 0 ? (
          <p className="text-xs text-gray-500 light:text-slate-500 py-4 text-center">
            {loading ? 'Loading…' : 'No predictions yet — the tracking scanner logs one per trading day. Check back after the next session.'}
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="text-gray-500 light:text-slate-500 uppercase tracking-wider text-[10px]">
                  <th className="text-left px-2 py-1.5 font-medium">Date</th>
                  <th className="text-center px-2 py-1.5 font-medium">Predicted</th>
                  <th className="text-right px-2 py-1.5 font-medium">Range</th>
                  <th className="text-center px-2 py-1.5 font-medium">Actual</th>
                  <th className="text-center px-2 py-1.5 font-medium">Direction</th>
                  <th className="text-center px-2 py-1.5 font-medium">Range Hit</th>
                  <th className="text-right px-2 py-1.5 font-medium">Fwd Return</th>
                </tr>
              </thead>
              <tbody>
                {predictions.map((p) => (
                  <tr key={p.id} className="border-t border-gray-800/40 light:border-slate-200">
                    <td className="px-2 py-1.5 text-gray-400 light:text-slate-500">{p.predictionDate}</td>
                    <td className="text-center px-2 py-1.5 font-medium">{p.predictedDirection}</td>
                    <td className="text-right px-2 py-1.5 tabular-nums text-gray-400 light:text-slate-500">
                      {formatIndianNumber(p.predictedRangeLow, 0)}–{formatIndianNumber(p.predictedRangeHigh, 0)}
                    </td>
                    <td className="text-center px-2 py-1.5">{p.resolved ? p.actualDirection ?? '—' : <span className="text-gray-600 light:text-slate-400 italic">pending</span>}</td>
                    <td className="text-center px-2 py-1.5">
                      {p.directionCorrect == null ? '—' : p.directionCorrect ? <span className="text-emerald-400">✓</span> : <span className="text-red-400">✕</span>}
                    </td>
                    <td className="text-center px-2 py-1.5">
                      {p.rangeAccurate == null ? '—' : p.rangeAccurate ? <span className="text-emerald-400">✓</span> : <span className="text-red-400">✕</span>}
                    </td>
                    <td className={`text-right px-2 py-1.5 tabular-nums font-medium ${p.forwardReturnPercent == null ? 'text-gray-500' : p.forwardReturnPercent >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                      {p.forwardReturnPercent != null ? `${p.forwardReturnPercent >= 0 ? '+' : ''}${p.forwardReturnPercent.toFixed(2)}%` : '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}

function AccuracyWindowCard({ title, window: w }: { title: string; window: PredictionAccuracyWindow }) {
  return (
    <Card>
      <div className="text-[10px] font-semibold text-gray-500 light:text-slate-500 uppercase tracking-wider mb-2">{title}</div>
      {w.resolvedCount === 0 ? (
        <p className="text-[11px] text-gray-500 light:text-slate-500">Not enough data yet</p>
      ) : (
        <>
          <div className="text-2xl font-bold tabular-nums text-gray-100 light:text-slate-900">{w.directionAccuracyPercent ?? '—'}%</div>
          <div className="text-[10px] text-gray-500 light:text-slate-500 mb-2">direction accuracy · {w.resolvedCount} resolved</div>
          <div className="flex justify-between text-[10px] text-gray-500 light:text-slate-500">
            <span>Range hit: {w.rangeAccuracyPercent ?? '—'}%</span>
            <span>Avg: {w.avgForwardReturnPercent != null ? `${w.avgForwardReturnPercent >= 0 ? '+' : ''}${w.avgForwardReturnPercent}%` : '—'}</span>
          </div>
        </>
      )}
    </Card>
  );
}

// --- Section 8 ---

function AlertsStatusCard({ onViewAlerts }: { onViewAlerts: () => void }) {
  const live = ['VIX Spike', 'PCR Extreme (NIFTY/BANKNIFTY)', 'Unusual F&O-Universe OI Activity', 'Significant Futures OI Change'];
  const pending = ['FII Buying > ₹3,000 Cr', 'FII Selling > ₹3,000 Cr'];
  return (
    <Card>
      <div className="flex items-center justify-between mb-3">
        <div className="flex flex-wrap gap-1.5">
          {live.map((l) => (
            <span key={l} className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 light:text-emerald-700 font-medium">✓ {l}</span>
          ))}
          {pending.map((l) => (
            <span key={l} className="text-[10px] px-2 py-0.5 rounded-full bg-gray-800 light:bg-slate-100 text-gray-500 light:text-slate-400 font-medium">✕ {l} (needs FII data)</span>
          ))}
        </div>
        <button onClick={onViewAlerts} className="text-[11px] text-emerald-400 light:text-emerald-700 hover:text-emerald-300 font-medium shrink-0 ml-3">
          View all alerts →
        </button>
      </div>
      <p className="text-[11px] text-gray-500 light:text-slate-500">Delivered via Terminal + Telegram, same channel as every other alert in this app.</p>
    </Card>
  );
}

// --- Sections 1, 2, 3, 9: not connected ---

function NotConnectedPanel() {
  const rows = [
    { section: 'Institutional Flow Dashboard', needs: 'NSE FII/DII cash-market bhavcopy (daily buy/sell value)' },
    { section: 'FII Futures Position Analysis', needs: "NSE's FII derivatives position report (index/stock futures long vs. short)" },
    { section: 'Participant-wise Open Interest', needs: 'NSE participant-wise OI report (FII / DII / Pro / Client)' },
    { section: 'Institutional Flow Screener', needs: 'Historical FII/DII flow + participant OI, for backtested next-day returns' },
  ];
  return (
    <Card accent="border-t-gray-600/50">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {rows.map((r) => (
          <div key={r.section} className="bg-gray-900/40 light:bg-slate-50 rounded-lg p-3 border border-gray-800/40 light:border-slate-200">
            <div className="text-xs font-semibold text-gray-400 light:text-slate-500 mb-1">{r.section}</div>
            <div className="text-[11px] text-gray-600 light:text-slate-400">Needs: {r.needs}</div>
          </div>
        ))}
      </div>
      <p className="text-[11px] text-gray-500 light:text-slate-500 mt-3 pt-3 border-t border-gray-800/60 light:border-slate-200">
        None of this is available through Angel One's API. Connecting an NSE data source (official feed, paid vendor, or a manual daily import) would unlock these sections without changing anything else on this page.
      </p>
    </Card>
  );
}
