// ============================================================
// CLI: STRUCTURE_ENTRY_MODE head-to-head — TOUCH vs REJECTION_CLOSE
// ============================================================
// npm run backtest-structure-entry-mode --workspace=@fno/server
//
// The question: does the engine wait for the next 15m candle before taking a
// trade? It already waits for the sweep close, the displacement close and the
// FVG-defining close. The live FILL, though, happens the instant price
// touches the zone (TOUCH) — even if that candle then closes straight through
// it. REJECTION_CLOSE instead waits for a closed candle that trades into the
// zone and closes back beyond its near edge, in the outer half of its own
// range (see @fno/analytics structure-engine/rejection-close.ts).
//
// PRE-REGISTERED PROTOCOL (fixed before this run):
//   - THE LIVE 15m config only (D1.0-NOGUARD, closing guard 60) — no variant
//     search; REJECTION_CLOSE has exactly one variant, so it runs ONCE.
//   - Same 12 months of 15m data, same masks, same 0.1R cost, same chronological
//     ⅔/⅓ split as every other structure backtest.
//   - Go-live rule: REJECTION_CLOSE becomes the default only if, on the
//     OUT-OF-SAMPLE period, its avg net R > TOUCH's AND its PF > TOUCH's AND
//     it has >= 20 trades. Otherwise TOUCH stays the default.
//   - TOUCH's OOS numbers were already seen in the main structure-report
//     (structure-report.md/json, D1.0-NOGUARD chosen in-sample there too) —
//     stated plainly below, not re-litigated.
//
// Writes structure-entry-mode-report.json / .md — a SEPARATE report; nothing
// existing (structure-report.*, structure-5m-report.*, momentum-report.*) is
// touched or regenerated by this script.
// ============================================================

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { STRUCTURE_VARIANTS, type StructureSetup, type StructureVariant } from '@fno/analytics';
import { BACKTEST_DATA_DIR } from '../backtest/fetch-history.js';
import {
  BACKTEST_SYMBOLS,
  COST_R,
  groupStats,
  loadSymbol,
  replayStrategy,
  splitDate,
  statsOf,
  type BacktestTrade,
  type LoadedSymbol,
  type ReplayWindow,
  type TradeStats,
  type UnfilledOrder,
} from '../backtest/harness.js';
import { STRUCTURE_STRATEGY, STRUCTURE_STRATEGY_REJECTION_CLOSE } from '../backtest/structure-backtest.js';

const INDEX = new Set(['NIFTY', 'BANKNIFTY', 'SENSEX']);
const LIVE_VARIANT: StructureVariant = STRUCTURE_VARIANTS.find((v) => v.id === 'D1.0-NOGUARD')!;

const fmtR = (n: number | null | undefined) => (n == null ? '—' : (n >= 0 ? '+' : '') + n.toFixed(3));
const fmtPct = (n: number | null) => (n == null ? '—' : `${(n * 100).toFixed(1)}%`);
const fmtPf = (n: number | null) => (n == null ? '—' : n === Infinity ? '∞' : n.toFixed(2));
const avg = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null);

type STrade = BacktestTrade<StructureSetup>;

/** dir * (fill price − the zone's TOUCH entry) / risk. Positive = REJECTION_CLOSE filled further along the move than TOUCH would have (a smaller realised reward); 0 for TOUCH itself. */
function entryShiftR(t: STrade): number | null {
  const entry = t.signal.entry;
  const stop = t.signal.stop;
  const fill = t.fill?.price;
  if (entry == null || stop == null || fill == null) return null;
  const risk = Math.abs(entry - stop);
  if (!(risk > 0)) return null;
  const dir = t.signal.direction === 'BEARISH' ? -1 : 1;
  return (dir * (fill - entry)) / risk;
}

interface ModeRun {
  trades: STrade[];
  unfilled: UnfilledOrder<StructureSetup>[];
  stats: TradeStats;
  missed: number;
  lowRr: number;
  invalidated: number;
  avgEntryShiftR: number | null;
}

function runMode(loaded: LoadedSymbol[], strategy: typeof STRUCTURE_STRATEGY | typeof STRUCTURE_STRATEGY_REJECTION_CLOSE, window: ReplayWindow): ModeRun {
  const trades: STrade[] = [];
  const unfilled: UnfilledOrder<StructureSetup>[] = [];
  for (const l of loaded) {
    const r = replayStrategy(l, strategy, LIVE_VARIANT, window);
    trades.push(...r.trades);
    unfilled.push(...r.unfilled);
  }
  const shifts = trades.map(entryShiftR).filter((x): x is number => x != null);
  return {
    trades,
    unfilled,
    stats: statsOf(trades),
    missed: unfilled.filter((u) => u.outcome === 'MISSED').length,
    lowRr: unfilled.filter((u) => u.outcome === 'LOW_RR').length,
    invalidated: unfilled.filter((u) => u.outcome === 'INVALIDATED').length,
    avgEntryShiftR: avg(shifts),
  };
}

const HEADER = '| Mode | Trades | Win % | Avg net R | PF | Max DD (R) | MISSED | LOW_RR | INVALIDATED | Avg entry shift (R) |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|';
function row(label: string, m: ModeRun): string {
  return `| ${label} | ${m.stats.trades} | ${fmtPct(m.stats.winRate)} | ${fmtR(m.stats.avgNetR)} | ${fmtPf(m.stats.profitFactor)} | ${m.stats.maxDrawdownR.toFixed(2)} | ${m.missed} | ${m.lowRr} | ${m.invalidated} | ${m.avgEntryShiftR == null ? '—' : fmtR(m.avgEntryShiftR)} |`;
}

function main() {
  const loaded: LoadedSymbol[] = [];
  const missing: string[] = ['FINNIFTY (no snapshot fetched — not backtested)'];
  for (const spec of BACKTEST_SYMBOLS) {
    const l = loadSymbol(BACKTEST_DATA_DIR, spec);
    if (l) loaded.push(l);
    else missing.push(`${spec.symbol} (snapshot missing)`);
  }
  if (loaded.length === 0) throw new Error(`No snapshots in ${BACKTEST_DATA_DIR} — run fetch-history.ts first`);

  const calendar = loaded.find((l) => l.spec.symbol === 'NIFTY') ?? loaded[0];
  const dates = calendar.series.sessionDates;
  const oosFrom = splitDate(dates);
  const first = dates[0];
  const last = [...loaded.flatMap((l) => l.series.sessionDates)].sort().at(-1)!;
  const dayBefore = (d: string) => new Date(Date.parse(`${d}T12:00:00Z`) - 86400000).toISOString().slice(0, 10);
  const inSample: ReplayWindow = { from: first, to: dayBefore(oosFrom) };
  const outOfSample: ReplayWindow = { from: oosFrom, to: last };

  const lines: string[] = [];
  const log = (s = '') => { lines.push(s); console.log(s); };

  log('# STRUCTURE_ENTRY_MODE — TOUCH vs REJECTION_CLOSE (Part 2, pre-registered)');
  log();
  log(`The live 15m config only: ${LIVE_VARIANT.id} (DISP_MULT ${LIVE_VARIANT.dispMult}, opening guard ${LIVE_VARIANT.openingGuard ? 'on' : 'off'}, closing guard 60). Same 12 months of 15m data as structure-report.md, same masks, ${COST_R}R cost per trade, same chronological ⅔/⅓ split.`);
  log(`In-sample ${inSample.from} → ${inSample.to}; out-of-sample ${outOfSample.from} → ${outOfSample.to}.`);
  log('Pre-registered go-live rule: REJECTION_CLOSE becomes the default only if, on the OUT-OF-SAMPLE period, its avg net R > TOUCH\'s AND its PF > TOUCH\'s AND it has >= 20 trades. Otherwise the default stays TOUCH. REJECTION_CLOSE has exactly one variant (no grid), so it is run once.');
  log();
  log('**Already seen.** TOUCH\'s out-of-sample numbers are the SAME numbers already reported for D1.0-NOGUARD in structure-report.md (that report chose D1.0-NOGUARD in-sample independently and ran it once out of sample) — repeated here only so the two modes sit in one table. They are not a fresh look.');
  log();
  log(`Excluded: ${missing.join('; ')}.`);
  log();

  const touchIs = runMode(loaded, STRUCTURE_STRATEGY, inSample);
  const rejIs = runMode(loaded, STRUCTURE_STRATEGY_REJECTION_CLOSE, inSample);
  log('## In-sample (context only — the go-live decision reads out-of-sample)');
  log();
  log(HEADER);
  log(row('TOUCH', touchIs));
  log(row('REJECTION_CLOSE', rejIs));
  log();

  const touchOos = runMode(loaded, STRUCTURE_STRATEGY, outOfSample);
  const rejOos = runMode(loaded, STRUCTURE_STRATEGY_REJECTION_CLOSE, outOfSample);
  log('## Out-of-sample — the decision');
  log();
  log(HEADER);
  log(row('TOUCH (already seen)', touchOos));
  log(row('REJECTION_CLOSE (run once)', rejOos));
  log();
  log('### By symbol (out-of-sample)');
  log();
  log(HEADER.replace('| Mode |', '| Symbol / mode |'));
  const bySymbol = (trades: STrade[]) => {
    const m = new Map<string, STrade[]>();
    for (const t of trades) m.set(t.symbol, [...(m.get(t.symbol) ?? []), t]);
    return [...m.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1));
  };
  for (const [symbol, ts] of bySymbol(touchOos.trades)) log(row(`${symbol} TOUCH`, { trades: ts, unfilled: [], stats: statsOf(ts), missed: 0, lowRr: 0, invalidated: 0, avgEntryShiftR: null }));
  for (const [symbol, ts] of bySymbol(rejOos.trades)) {
    const shifts = ts.map(entryShiftR).filter((x): x is number => x != null);
    log(row(`${symbol} REJECTION_CLOSE`, { trades: ts, unfilled: [], stats: statsOf(ts), missed: 0, lowRr: 0, invalidated: 0, avgEntryShiftR: avg(shifts) }));
  }
  log();

  const passRR = (rejOos.stats.avgNetR ?? -Infinity) > (touchOos.stats.avgNetR ?? -Infinity);
  const passPF = (rejOos.stats.profitFactor ?? -Infinity) > (touchOos.stats.profitFactor ?? -Infinity);
  const passN = rejOos.stats.trades >= 20;
  const goLive = passRR && passPF && passN;
  log('## Go-live decision');
  log();
  log(`- avg net R: REJECTION_CLOSE ${fmtR(rejOos.stats.avgNetR)} ${passRR ? '>' : '<='} TOUCH ${fmtR(touchOos.stats.avgNetR)} — ${passRR ? 'PASS' : 'FAIL'}`);
  log(`- PF: REJECTION_CLOSE ${fmtPf(rejOos.stats.profitFactor)} ${passPF ? '>' : '<='} TOUCH ${fmtPf(touchOos.stats.profitFactor)} — ${passPF ? 'PASS' : 'FAIL'}`);
  log(`- trades: REJECTION_CLOSE ${rejOos.stats.trades} ${passN ? '>=' : '<'} 20 — ${passN ? 'PASS' : 'FAIL'}`);
  log();
  log(
    goLive
      ? '**PASS all three — STRUCTURE_ENTRY_MODE default becomes REJECTION_CLOSE.**'
      : '**FAIL at least one check — STRUCTURE_ENTRY_MODE default stays TOUCH** (REJECTION_CLOSE remains available, opt-in via STRUCTURE_ENTRY_MODE=REJECTION_CLOSE).'
  );
  log();

  const report = {
    generatedAt: new Date().toISOString(),
    liveVariant: LIVE_VARIANT,
    inSample,
    outOfSample,
    costR: COST_R,
    excluded: missing,
    inSampleResults: { TOUCH: { stats: touchIs.stats, missed: touchIs.missed, lowRr: touchIs.lowRr, invalidated: touchIs.invalidated }, REJECTION_CLOSE: { stats: rejIs.stats, missed: rejIs.missed, lowRr: rejIs.lowRr, invalidated: rejIs.invalidated, avgEntryShiftR: rejIs.avgEntryShiftR } },
    outOfSampleResults: {
      TOUCH: { stats: touchOos.stats, missed: touchOos.missed, lowRr: touchOos.lowRr, invalidated: touchOos.invalidated, bySymbol: groupStats(touchOos.trades, (t) => t.symbol) },
      REJECTION_CLOSE: { stats: rejOos.stats, missed: rejOos.missed, lowRr: rejOos.lowRr, invalidated: rejOos.invalidated, avgEntryShiftR: rejOos.avgEntryShiftR, bySymbol: groupStats(rejOos.trades, (t) => t.symbol) },
    },
    decision: { passRR, passPF, passN, goLive, default: goLive ? 'REJECTION_CLOSE' : 'TOUCH' },
    alreadySeen: 'TOUCH out-of-sample numbers repeat structure-report.md (D1.0-NOGUARD); REJECTION_CLOSE is the only fresh out-of-sample look in this report.',
  };
  writeFileSync(join(BACKTEST_DATA_DIR, 'structure-entry-mode-report.json'), JSON.stringify(report, null, 2));
  writeFileSync(join(BACKTEST_DATA_DIR, 'structure-entry-mode-report.md'), lines.join('\n'));
  console.log(`\nWrote ${join(BACKTEST_DATA_DIR, 'structure-entry-mode-report.md')}`);
}

try {
  main();
} catch (err: any) {
  console.error('Structure entry-mode backtest failed:', err);
  process.exit(1);
}
